// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1cz6MiY7WevLP5QdLki_23ZfFw009PGo',
    appId: '1:132521012360:web:f59d71eeda4d06ea7ec33d',
    messagingSenderId: '132521012360',
    projectId: 'echo-40d4d',
    authDomain: 'echo-40d4d.firebaseapp.com',
    storageBucket: 'echo-40d4d.appspot.com',
    measurementId: 'G-W157YM4EL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhzDEI6B2B2ovB_MqpNqI5i8QhWzTpbXE',
    appId: '1:132521012360:android:ec6f4f5ba1b7d0b27ec33d',
    messagingSenderId: '132521012360',
    projectId: 'echo-40d4d',
    storageBucket: 'echo-40d4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn9OKtI6lYBt1n9_PPHAzptSnkKPwXVyA',
    appId: '1:132521012360:ios:d4686b3c59ba3b477ec33d',
    messagingSenderId: '132521012360',
    projectId: 'echo-40d4d',
    storageBucket: 'echo-40d4d.appspot.com',
    iosBundleId: 'com.example.echo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn9OKtI6lYBt1n9_PPHAzptSnkKPwXVyA',
    appId: '1:132521012360:ios:d4686b3c59ba3b477ec33d',
    messagingSenderId: '132521012360',
    projectId: 'echo-40d4d',
    storageBucket: 'echo-40d4d.appspot.com',
    iosBundleId: 'com.example.echo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1cz6MiY7WevLP5QdLki_23ZfFw009PGo',
    appId: '1:132521012360:web:c73bd485a79ca1397ec33d',
    messagingSenderId: '132521012360',
    projectId: 'echo-40d4d',
    authDomain: 'echo-40d4d.firebaseapp.com',
    storageBucket: 'echo-40d4d.appspot.com',
    measurementId: 'G-RLWVF7DFQK',
  );
}
